### ISSUE TITLE
Possibility to set options? 

### ISSUE THREAD

**Issue by danielkoller** [thumbmarkjs/thumbmarkjs#10]
Hi @ilkkapeltola, great project - thanks for your hard work! 

If I may, I'd propose an enhancement: I'd like to set options like here -> https://github.com/damianobarbati/get-browser-fingerprint

I think that would make a great addition to Thumbmarkjs.

Thanks and keep up your great work!

**Comment by ilkkapeltola** [comment]
Yeah, absolutely.
I've actually thought about this a couple of days ago.
What kind of options would you need? Do you have a use case?

**Comment by danielkoller** [comment]
I thought about disabling the check of screen sizes, as users might use different screen sizes. I think it would be also beneficial to give the options to disable components - like for example for performance reasons. Thanks for answering and taking the time to look into this Issue.

**Comment by ilkkapeltola** [comment]
There's no check for screen size, due to the reason you mention: people can have multiple screens.
And I don't want the fingerprint to change depending on which screen the browser is on.
But performance reasons is a good point. For example, checking for permissions in the browser takes by far most time right now, and while it's only 20 milliseconds, it's maybe not an investment everyone wants to make.

By the way, it's still undocumented, but there's a method getFingerprintPerformance, which returns the components along with an 'elapsed' key that tells the milliseconds it took to resolve each of the component function promises.

**Comment by danielkoller** [comment]
Sorry about that. I tried a lot of different fingerprinting packages the last few days and must have missed that yours doesn't use the screen sizes. 

I just tested it on my device with getFingerprintPerformance and the total was 57.30 milliseconds. We just have a lot of users with older devices, so I had some sort of optimization in the back of my head.

**Comment by ilkkapeltola** [comment]
Yeah the total 57.30 is only the component promises. That's the amount that can easily be switched on and off.
Then, there's probably a lot of other kinds of optimizations that could be looked into.
If I just run this in a console:

```
const now = performance.now();
const datas = await ThumbmarkJS.getFingerprint();
const then = performance.now();
console.log(datas, then-now);
    ```

Then I get around 140ms end-to-end. I'm not a code optimization expert, but there's overhead in the library other than just the fingerprinting components. The bundler settings might be bad or something. I might need some help with that from more skilled developers, or learn to do it myself.

What's your use case? Can you elaborate how performance affects it?

**Comment by danielkoller** [comment]
I would use your project to detect unusual login behavior. We would store and compare fingerprints and send out mails, if we detect a new device. The Next.js project is already pretty big, so I am just trying ways to optimize some stuff. But like I mentioned, I am not really concerned anymore about your project's performance. :)

**Comment by ilkkapeltola** [comment]
btw,
> I tried a lot of different fingerprinting packages the last few days and must have missed that yours doesn't use the screen sizes.

Did you choose this one? If so, what were the deciding factors?
Is there something I can do to further improve it? (apart from options, which were covered)

**Comment by danielkoller** [comment]
Yeah, I've chosen this one and presented it to my team already. No further improvements from my side, thanks. I will come back to you, if I stumble over some other stuff when implementing and using in production.

**Comment by mict-ss** [comment]
> Yeah, absolutely. I've actually thought about this a couple of days ago. What kind of options would you need? Do you have a use case? Are you thinking about enabling/disabling some of the components?

Use case:
Leave out the browser version, so the device fingerprint remains the same after a browser update.

Is that an option?

**Comment by ilkkapeltola** [comment]
Right. Okay. I can see how this can be useful...

**Comment by HashGateApp** [comment]
Another use case that I've just come across...

Web3 apps that are loaded inside of a wallet on iOS via iFrame request payment information which results in this error 
``` 
SecurityError: Third-party iframes are not allowed to request payments unless explicitly allowed via Feature-Policy (payment)
```

Being able to modularly control which browser tests are used similar to https://mattbrailsford.github.io/imprintjs/ would be huge

**Comment by ilkkapeltola** [comment]
Okay. I'll work on this next.

**Comment by ilkkapeltola** [comment]
my plan would be to expose a attribute called `options`.
It could for example have a key like `exclude` which would take a list of strings.
Those could be e.g. a top level component `webgl` in which case the whole component would never run.
Or, you could have more specific paths like `system.browser.version` in which case the component `system` would run, but before the fingerprint has was taken, the element `version` in `browser` would be taken out.
And obviously could be used mixed:

```
ThumbmarkJS.options = { exclude: ['webgl', 'system.browser.version'] }
```

Would that sound like a good solution?

@HashGateApp as for this error, let's see if I can catch that error and fail silently. I think it's a much better solution than people disabling a feature because of an error. The library should be more robust.

**Comment by ilkkapeltola** [comment]
There's a new version that adds options like this. Have a look.

**Comment by danielkoller** [comment]
Well done, thanks!

**Comment by ilkkapeltola** [comment]
Closing this issue, please re-open if needed or add a new one.
