### ISSUE TITLE
Different fingerprint but same json data

### ISSUE THREAD

**Issue by disagol** [thumbmarkjs/thumbmarkjs#53]
Hey, thanks for this useful neat library. In chrome when opening the demo page for  [thumbmarkjs](https://github.com/thumbmarkjs/thumbmarkjs) I get a fp but the thing is when adding the library in my web app and calling the getFingerprint method in this very same browser I get a different value. I compare both ThumbmarkJS.getFingerprintData() and are the same. What am I missing? Has this something to do with the hashing function or perhaps other config via setOptions?

Thanks in advance. I’m looking forward to your reply.

**Comment by ilkkapeltola** [comment]
I'll have to look into this. This could be due to something taking a bit of time to load, for example the fonts.
The demo page does multiple calls to the library, and I have tried to ensure that the results are always the same, but it could be that the first call doesn't get all the same info from the browser, but the second call that gets the components, is crucially a few ms later.

I am not sure yet how to debug this, but certainly different components would result in a different thumbmark.

I'll improve the demo page so that only one call is made that returns the components and the thumbmark, then we can check where the difference is.

**Comment by ilkkapeltola** [comment]
This is now done so that there's only a single call to getFingerprint that updates both the hash and the data that was used to calculate it, so the components should always match the hash.
